---
services:
  build_app:
    build: java_webapp
    volumes:
      -
        source: war_file
        target: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
        type: volume
  run_app:
    image: "tomcat:9"
    ports:
      - "8080:8080"
#    volumes:
#      -
#        source: war_file
#        target: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
#        type: volume
version: "3.2"
volumes:
  war_file: ~